name: Bug report
description: Report a defect or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? What did you expect instead?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, .NET, Docker, DB versions
