name: CI

on:
  push:
    branches:
      - develop
      - master
      - feat/**
      - fix/**
      - chore/**
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      DOTNET_NOLOGO: 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore WebhookInbox.sln

      - name: Build
        run: dotnet build WebhookInbox.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test WebhookInbox.sln --configuration Release --no-build --verbosity normal
