name: Enforce linked issue
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check-issue-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR for closing keywords
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const title = context.payload.pull_request.title || "";
            const re = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+/i;
            if (!re.test(body) && !re.test(title)) {
              core.setFailed('PR must reference an issue with "Closes #<id>" (or Fixes/Resolves).');
            }
